# Change these first
owner: sk5s # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: sk5s.cyou
    url: https://sk5s.cyou/
  - name: alsoweather-website
    url: https://sk5s.cyou/alsoweather/
  - name: sk5short-website
    url: https://sk5s.cyou/sk5short/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.sk5s.cyou
  # baseUrl: /your-repo-name
  logoUrl: https://i.imgur.com/3LvCEXa.png
  name: sk5s uptime
  introTitle: "**sk5s project** uptime monitor and status page."
  introMessage: "![](https://sk5s.cyou/sk5s/ad/sk5s-project.gif)"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER
    - title: sk5s site
      href: https://sk5s.cyou/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
